---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gha-exporter.fullname" . }}
  labels:
    {{- include "gha-exporter.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "gha-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gha-exporter.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --app-id
            - {{ required "Missing .Values.exporter.githubApp.id" .Values.exporter.githubApp.id | quote }}
            - --owner
            - {{ required "Missing .Values.exporter.repoOwner" .Values.exporter.repoOwner | quote}}
            - --repos
            - {{ join "," (required "Missing .Values.exporter.repos" .Values.exporter.repos) | quote}}
            {{- if .Values.exporter.pollingTime }}
            - --sleep
            - {{ .Values.exporter.pollingTime | quote }}
            {{- end }}
            {{- if .Values.exporter.backfill.enabled }}
            - --backfill
            - "true"
            {{- if .Values.exporter.backfill.initialWindow }}
            - --initial-window
            - {{ .Values.exporter.backfill.initialWindow | quote }}
            {{- end }}
            {{- end }}
          envFrom:
            - secretRef:
                name: {{ include "gha-exporter.secret.name" . }}
                optional: false
          ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
