{{- if eq (include "gha-exporter.secret.enabled" .) "true" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gha-exporter.secret.name" . }}
  labels:
    {{- include "gha-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
    GHA_APP_KEY: {{ .Values.exporter.githubApp.privateKey }}
{{- else }}
{{- $_ := required 
  ".Values.exporter.githubApp.privateKey or .Values.exporter.githubApp.privateKeySecretName must be set" 
  .Values.exporter.githubApp.privateKeySecretName 
-}}
{{- end }}
