{
 "title": "GitHub Actions workflows",
 "tags": [ "github" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "group",
    "label": "Group by",
    "query": "repo, workflow, ref, event_type"
   },
   {
    "name": "repo",
    "label": "Repo",
    "query": {
     "query": "label_values(gha_workflow_run_count,repo)"
    }
   },
   {
    "name": "ref",
    "label": "Git ref",
    "query": {
     "query": "label_values(gha_workflow_run_count{repo=~\"$repo\"},ref)"
    }
   },
   {
    "name": "workflow",
    "label": "Workflow",
    "query": {
     "query": "label_values(gha_workflow_run_count{repo=~\"$repo\", ref=~\"$ref\"},workflow)"
    }
   },
   {
    "name": "event",
    "label": "Event type",
    "query": {
     "query": "label_values(gha_workflow_run_count{repo=~\"$repo\", ref=~\"$ref\", workflow=~\"$workflow\"},event_type)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Workflow pass rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by(${group:csv}) (gha_workflow_run_count{conclusion=`success`, repo=~`${repo:regex}`, workflow=~`${workflow:regex}`, ref=~`${ref:regex}`, event_type=~`${event:regex}`})  / sum by(${group:csv}) (gha_workflow_run_count{conclusion=~`(success|failure)`, repo=~`${repo:regex}`, workflow=~`${workflow:regex}`, ref=~`${ref:regex}`, event_type=~`${event:regex}` }))"
    }
   ]
  },
  { "title": "Workflow time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Average workflow runner time",
   "type": "timeseries",
   "description": "The total run time of all runners for a workflow run",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase((sum by(${group:csv}) (gha_workflow_runner_seconds{repo=~`${repo:regex}`, workflow=~`${workflow:regex}`, ref=~`${ref:regex}`, event_type=~`${event:regex}`}))[$__interval:]) / (increase((sum by(${group:csv}) (gha_workflow_run_count{conclusion=\"success\", repo=~`${repo:regex}`, workflow=~`${workflow:regex}`, ref=~`${ref:regex}`, event_type=~`${event:regex}`}))[$__interval:]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average workflow elapsed time",
   "type": "timeseries",
   "description": "The total elapsed, \"wall clock\" time of all runners for a workflow run",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase((sum by(${group:csv}) (gha_workflow_elapsed_seconds{repo=~`${repo:regex}`, workflow=~`${workflow:regex}`, ref=~`${ref:regex}`, event_type=~`${event:regex}`}))[$__interval:]) / (increase((sum by(${group:csv}) (gha_workflow_run_count{conclusion=\"success\", repo=~`${repo:regex}`, workflow=~`${workflow:regex}`, ref=~`${ref:regex}`, event_type=~`${event:regex}`}))[$__interval:]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}